var bike = "Honda";
console.log("Is bike == 'Kawasaki'? I predict False");
console.log(bike == "Kawasaki");
var food = "Burger";
console.log("Is food == 'Burger'? I predict True");
console.log(food == "Burger");
var shoe = "Bata";
console.log("Is shoe == 'Service'? I predict False");
console.log(shoe == "Service");
var movie = "Terminator";
console.log("Is movie == 'Terminator'? I predict True");
console.log(movie == "Terminator");
var street = "44th Street";
console.log("Is street == '45th Street'? I predict False");
console.log(street == "45th Street");
var station = "Karachi";
console.log("Is station == 'Karachi'? I predict True");
console.log(station == "Karachi");
var color = "Orange";
console.log("Is color == 'Purple'? I predict False");
console.log(color == "Purple");
var software = "Photoshop";
console.log("Is software == 'Photoshop'? I predict True");
console.log(software == "Photoshop");
var medicine = "Ponstan";
console.log("Is medicine == 'Brufen'? I predict False");
console.log(medicine == "Brufen");
var cigarette = "Dunhil";
console.log("Is cigarette == 'Dunhil'? I predict True");
console.log(cigarette == "Dunhil");
